MVCWebApp/Models/AddEmployeeViewModel.cs
namespace MVCWebApp.Models
{
    public class AddEmployeeViewModel
    {   
        public string Name { get; set; } = "ducdoom";
        public string Email { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
    }
}

MVCWebApp/Models/Domain/Employee.cs
namespace MVCWebApp.Models.Domain
{
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; } = string.Empty;
        public string Email { get; set; } = string.Empty;
        public string Phone { get; set; } = string.Empty;
    }
}

MVCWebApp/Models/ErrorViewModel.cs
namespace MVCWebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCWebApp/Models/ManyAff/Dashboard.cs
namespace MVCWebApp.Models.ManyAff
{
    public class Dashboard
    {
        public Dashboard()
        {
            
        }

        public ManyaffClient.Responses.DataCard ViewNum = new();
        public ManyaffClient.Responses.DataCard SubmitFormNum = new();
        public ManyaffClient.Responses.DataCard PaidOrderNum = new();
        public ManyaffClient.Responses.DataCard JoinedCampaign = new();
        public ManyaffClient.Responses.DataCard Commission = new();
        public ManyaffClient.Responses.DataCard ValidCommission = new();
        public ManyaffClient.Responses.DataCard HoldCommission = new();
        public ManyaffClient.Responses.DataCard CancelCommission = new();
        public ManyaffClient.Responses.DataCard PaidCommission = new();
        public ManyaffClient.Responses.DataCard RemainingPaidCommission = new();
    }
}

MVCWebApp/Models/ManyAff/UserDashboard.cs
namespace MVCWebApp.Models.ManyAff
{
    public class UserDashboard
    {
        public string Email { get; set; } = string.Empty;
        public string Password { get; set; } = string.Empty;
        public Dashboard Dashboard { get; set; } = new();
    }
}

MVCWebApp/Models/PublisherViewModel.cs
using ManyaffClient.Responses;
using MVCWebApp.Models.ManyAff;
using System.Text.Json;

namespace MVCWebApp.Models
{
    public class PublisherViewModel
    {
        private readonly ManyaffClient.ManyaffClient manyaffClient = new();
        private HttpClient httpClient = new();

        public List<ManyaffClient.User> Users { get; set; } = new();
        public PublisherViewModel()
        {
            Users =
                [
                    new ManyaffClient.User { Email = "pub1@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub2@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub3@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub4@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub5@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub6@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub7@gmail.com", Password = "123456" },
                    new ManyaffClient.User { Email = "pub8@gmail.com", Password = "123456" },
                ];
        }

        public DateTime StartDate = DateTime.Now;
        public DateTime EndDate = DateTime.Now;

        public List<UserDashboard> UserDashboards { get; set; } = new();

        public async Task GetUserDashboard()
        {
            UserDashboards.Clear();

            foreach (ManyaffClient.User user in Users)
            {
                DashboardReponse dashboardReponse = await manyaffClient.GetUserDashboard(user, StartDate, EndDate);
                DataCard dataCard = dashboardReponse.Data.DataCard[0];
                Dashboard dashboard = new()
                {
                    ViewNum = dashboardReponse.Data.DataCard[0],
                    SubmitFormNum = dashboardReponse.Data.DataCard[1],
                    PaidOrderNum = dashboardReponse.Data.DataCard[2],
                    JoinedCampaign = dashboardReponse.Data.DataCard[3],
                    Commission = dashboardReponse.Data.DataCard[4],
                    ValidCommission = dashboardReponse.Data.DataCard[5],
                    HoldCommission = dashboardReponse.Data.DataCard[6],
                    CancelCommission = dashboardReponse.Data.DataCard[7],
                    PaidCommission = dashboardReponse.Data.DataCard[8],
                    RemainingPaidCommission = dashboardReponse.Data.DataCard[9]
                };

                UserDashboard userDashboard = new()
                {
                    Email = user.Email,
                    Password = user.Password,
                    Dashboard = dashboard
                };

                UserDashboards.Add(userDashboard);
            }

            string a = "a";
            //return UserDashboards;
        }

    }
}

MVCWebApp/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;

namespace MVCWebApp.Controllers
{
    public class EmployeeController : Controller
    {
        public IActionResult Add()
        {
            AddEmployeeViewModel model = new()
            {
                Name = "ducdoom"
            };
            return View(model);
        }

        public IActionResult Save(AddEmployeeViewModel model)
        {

            string a = model.Name;
            return View();
        }

    }
}

MVCWebApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;
using System.Diagnostics;

namespace MVCWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCWebApp/Controllers/PublisherController.cs
using Microsoft.AspNetCore.Mvc;
using MVCWebApp.Models;

namespace MVCWebApp.Controllers
{
    public class PublisherController : Controller
    {
        private PublisherViewModel publisherViewModel = new();
        public async Task<IActionResult> Index()
        {
            await publisherViewModel.GetUserDashboard();
            return View(publisherViewModel);
        }
    }
}

MVCWebApp/Views/Employee/Add.cshtml
@model MVCWebApp.Models.AddEmployeeViewModel


@{

}

<h2>Add2</h2>
<div>
    <input class="form-control" type="text" asp-for="Name">
    <button class="btn btn-primary" asp-controller="Employee" asp-action="Add">Click me</button>
    <button class="btn btn-success" asp-controller="Employee" asp-action="Save">Save</button>

</div>

MVCWebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCWebApp/Views/Publisher/Index.cshtml
@model PublisherViewModel
@{
}

<table class="table table-bordered table-striped table-responsive">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            @* <th scope="col">Password</th> *@
            <th scope="col">Số lượt view</th>
            <th scope="col">Số lượt submit form</th>
            <th scope="col">Số order đã thanh toán</th>
            <th scope="col">Số chiến dịch đã tham gia</th>
            <th scope="col">Hoa hồng phát sinh</th>
            <th scope="col">Hoa hồng hợp lệ</th>
            <th scope="col">Hoa hồng bị giữ</th>
            <th scope="col">Hoa hồng bị huỷ</th>
            <th scope="col">Hoa hồng đã chi trả</th>
            <th scope="col">Hoa hồng còn được chi trả</th>
        </tr>
    </thead>
    <tbody>
        @{
            int count = 1;
        }
        @foreach (var item in Model.UserDashboards)
        {
            <tr>
                <th scope="row">@count</th>
                <td>@item.Email</td>
                @* <td>@item.Password</td> *@
                <td>@item.Dashboard.ViewNum.Value</td>
                <td>@item.Dashboard.SubmitFormNum.Value</td>
                <td>@item.Dashboard.PaidOrderNum.Value</td>
                <td>@item.Dashboard.JoinedCampaign.Value</td>
                <td>@item.Dashboard.Commission.Value.ToString("N0")</td>
                <td>@item.Dashboard.ValidCommission.Value.ToString("N0")</td>
                <td>@item.Dashboard.HoldCommission.Value.ToString("N0")</td>
                <td>@item.Dashboard.CancelCommission.Value.ToString("N0")</td>
                <td>@item.Dashboard.PaidCommission.Value.ToString("N0")</td>
                <td>@item.Dashboard.RemainingPaidCommission.Value.ToString("N0")</td>

            </tr>
            count++;
        }
    </tbody>
</table>

MVCWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVCWebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCWebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Add">Add employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Publisher" asp-action="Index">Publishers</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MVCWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>